// Writes abi/index.ts from the forge artifacts so the web app and the relayer import typed ABIs
// (`as const` → viem infers every function and event). Run after `forge build`; `--check` fails when the
// committed file is stale and skips cleanly when there are no artifacts (Node-only CI job).
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const artifacts = [
  ["turnstileEventAbi", "out/TurnstileEvent.sol/TurnstileEvent.json"],
  ["turnstileFactoryAbi", "out/TurnstileFactory.sol/TurnstileFactory.json"],
  ["erc2771ForwarderAbi", "out/ERC2771Forwarder.sol/ERC2771Forwarder.json"],
];

if (!existsSync(join(root, "out"))) {
  console.log("[contracts] out/ missing — run `forge build` first (skipping abi export)");
  process.exit(0);
}

let source = "// Generated by scripts/export-abi.mjs from the forge artifacts — do not edit by hand.\n\n";
for (const [name, file] of artifacts) {
  const { abi } = JSON.parse(readFileSync(join(root, file), "utf8"));
  source += `export const ${name} = ${JSON.stringify(abi)} as const;\n\n`;
}

const target = join(root, "abi/index.ts");
const tmp = join(root, "abi/.index.tmp.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(tmp, source);
const fmt = spawnSync("pnpm", ["exec", "biome", "format", "--write", tmp], { cwd: root, stdio: "inherit" });
if (fmt.status !== 0) process.exit(fmt.status ?? 1);
const formatted = readFileSync(tmp, "utf8");
spawnSync("rm", ["-f", tmp]);

if (check) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== formatted) {
    console.error("[contracts] abi/index.ts is stale — run `pnpm --filter @turnstile/contracts abi`");
    process.exit(1);
  }
  console.log("[contracts] abi/index.ts is up to date");
} else {
  writeFileSync(target, formatted);
  console.log(`[contracts] wrote ${target}`);
}
