#!/usr/bin/env node
// Rewrites the `chains:` block of config.yaml from packages/contracts/deployments/<chainId>.json so the
// indexer always points at the factory the app and relayer use. Local anvil (31337) is skipped: HyperSync
// has no view of it and the indexer is not part of the local loop. Usage: pnpm sync-config [--check]
import fs from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const configPath = path.join(here, "..", "config.yaml");
const deployments = path.join(here, "..", "..", "contracts", "deployments");
const NAMES = { 143: "Monad", 10143: "Monad testnet" };

const files = fs.existsSync(deployments)
  ? fs
      .readdirSync(deployments)
      .filter((f) => /^\d+\.json$/.test(f))
      .sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10))
  : [];

const chains = files
  .map((f) => JSON.parse(fs.readFileSync(path.join(deployments, f), "utf8")))
  .filter((d) => d.chainId !== 31337 && d.factory);

const lines = [];
if (chains.length === 0) {
  lines.push(
    "  - id: 10143 # Monad testnet — pending deployment (deployments/10143.json)",
    "    start_block: 0",
    "    contracts:",
    "      - name: TurnstileFactory",
    '        address: "0x0000000000000000000000000000000000000000"',
    "      - name: TurnstileEvent # registered dynamically from EventCreated",
  );
}
for (const d of chains) {
  lines.push(
    `  - id: ${d.chainId} # ${NAMES[d.chainId] ?? `chain ${d.chainId}`}`,
    `    start_block: ${d.deployedAtBlock ?? 0}`,
    "    contracts:",
    "      - name: TurnstileFactory",
    `        address: "${d.factory}"`,
    "      - name: TurnstileEvent # registered dynamically from EventCreated",
  );
}

const config = fs.readFileSync(configPath, "utf8");
const begin = "  # --- generated by scripts/sync-config.mjs from packages/contracts/deployments/*.json ---\n";
const end = "  # --- end generated ---\n";
const a = config.indexOf(begin);
const b = config.indexOf(end);
if (a < 0 || b < 0) throw new Error("config.yaml: generated markers missing");
const next = `${config.slice(0, a + begin.length)}${lines.join("\n")}\n${config.slice(b)}`;

if (process.argv.includes("--check")) {
  if (next !== config) {
    console.error("config.yaml is out of date with packages/contracts/deployments — run `pnpm sync-config`");
    process.exit(1);
  }
  console.log("config.yaml matches deployments/");
} else {
  fs.writeFileSync(configPath, next);
  console.log(
    chains.length
      ? `config.yaml → ${chains.map((c) => `${c.chainId} @ ${c.factory}`).join(", ")}`
      : "config.yaml → placeholder (no testnet deployment yet)",
  );
}
